

export const SINGLE_USER_REQUEST = "SINGLE_USER_REQUEST"

export const SINGLE_USER_SUCCESS = "SINGLE_USER_SUCCESS"

export const SINGLE_USER_FAILURE = "SINGLE_USER_FAILURE"

export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE"

export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
