export const GET_MY_POST_REQUEST = "GET_MY_POST_REQUEST"

export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS"

export const GET_MY_POST_FAILURE = "GET_MY_POST_FAILURE"

export const UPLOAD_POST_LOADING = "UPLOAD_POST_LOADING";

export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS";

export const UPLOAD_POST_FAILURE = "UPLOAD_POST_FAILURE";

export const DELETE_POST = "DELETE_POST";