export const GET_POST_LOADING = "GET_POST_LOADING";

export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const GET_LIKE_UNLIKE = "GET_LIKE_UNLIKE";

export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";

export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";









