export const GET_USER_LOADING = "GET_USER_LOADING"

export const GET_USER_SUCCESS = "GET_USER_SUCCESS"

export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const UPDATE_USERPROFILE_LOADING = "UPDATE_USERPROFILE_LOADING"

export const UPDATE_USERPROFILE_SUCCESS = "UPDATE_USERPROFILE_SUCCESS"

export const UPDATE_USERPROFILE_FAILURE = "UPDATE_USERPROFILE_FAILURE"

export const UPDATE_PASSWORD_LOADING = "UPDATE_PASSWORD_LOADING"

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"

export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE"